### ISSUE TITLE
Non-conformable arguments

### ISSUE THREAD

**Issue by hiramponce** [jroberayalas/ahnr#1]
`Error in Phi %*% H[[i]] : non-conformable arguments`
This error appeared when using the `SimAHNnD` function. 
 
The Quick Example about SISO system was executed and the parameters of the artificial hydrocarbon networks were modified to those below (focus on the number of molecules `m = 10`):
`ahn <- AHNnD(Sigma, 10, 0.01, 500)`

It was tested with values of molecules more than 8 and the same error was found.

**Guess:** matrices `Phi `and `H` are of different dimensions. Probably, `Phi` is not well computed.

**Comment by jroberayalas** [comment]
SOLVED
