### ISSUE TITLE
Mistake in comment: visualize an AHN

### ISSUE THREAD

**Issue by hiramponce** [jroberayalas/ahnr#2]
In the vignette, there is a mistake in the explanation line about [visualize an artificial hydrocarbon network](https://github.com/jroberayalas/ahnr/blob/master/vignettes/ahn.Rmd#simulate-an-artificial-hydrocarbon-network):

> To visualize the performance of the compound, the following code can be used:

Please, replace it with:

> To visualize the performance of the mixture, the following code can be used:

**Comment by jroberayalas** [comment]
Done!
